### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by xsk0802** [junyuchen245/Fully_Unsupervised_CNN_Registration_Keras#1]
Hello, can you provide the two datasets ：   xcat_pat_1.npz  、CT_p1.npz 
Thank you very much

**Comment by junyuchen245** [comment]
Hi,

Unfortunately, due to some restrictions, I cannot share those images. However, the patient CT scans used in this study were obtained from a publicly available dataset, The Cancer Imaging Archive: https://www.cancerimagingarchive.net/
The specific dataset we used is the NaF Prostate dataset: https://wiki.cancerimagingarchive.net/display/Public/NaF+Prostate.

Regarding the XCAT phantom, you will need to apply for a license in order to use the phantom, either from: 
https://olv.duke.edu/technologies/4d-extended-cardiac-torso-xcat-phantom-version-2-0/
or from:
http://jhu.technologypublisher.com/technology/16326

Thanks,
Junyu

**Comment by junyuchen245** [comment]
Hi,

I uploaded an example image pair to "CNNReg_MedPhy_TF2x". After extracting the "pat.pkl" file from "img.zip", you should be able to run the script "register3D_pat.py". Note that this script can take about 16 GB of GPU memory, because of the size of the image volumes.

Thanks,
Junyu
